version: '3'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=rudy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
  web:
    build: .
    command: web
    ports:
      - 3000:3000
