version: '3'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=rudy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
  pgadmin4:
    image: thajeztah/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:5050"
  web:
    build: .
    command: web
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
